server = "myserver.local:5258"
certificate = "/etc/rkvm/certificate.pem"

# This is to prevent malicious clients from connecting to the server.
# Make sure this matches your server's config.
#
# Change this to your own value before deploying rkvm.
password = "123456789"

# Optional values.
# Make sure these match what you have in your server's config.

# Message read timeout.
# read-timeout = "500ms"
# Message write timeout.
# write-timeout = "500ms"
# TLS handshake timeout.
# tls-timeout = "500ms"