[package]
name = "rkvm-config"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
humantime = "2.1.0"
serde = { version = "1.0.204", features = ["derive"] }

[dev-dependencies]
toml = "0.8.14"
