[package]
name = "rkvm-client"
license = "MIT"
version = "0.7.0"
authors = ["Jan Trefil <8711792+htrefil@users.noreply.github.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.53.1", features = ["macros", "time", "fs", "net", "signal", "rt-multi-thread", "sync"] }
rkvm-input = { path = "../rkvm-input" }
rkvm-net = { path = "../rkvm-net" }
serde = { version = "1.0.229", features = ["derive"] }
toml = "1.1.6"
env_logger = "0.11.11"
clap = { version = "4.6.7", features = ["derive"] }
thiserror = "2.0.20"
tokio-rustls = "0.26.5"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }

[package.metadata.rpm]
package = "rkvm-client"

[package.metadata.rpm.cargo]
buildflags = ["--release"]

[package.metadata.rpm.targets]
client = { path = "/usr/bin/rkvm-client" }
