[package]
name = "rkvm-input"
version = "0.1.0"
authors = ["Jan Trefil <8711792+htrefil@users.noreply.github.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.229", features = ["derive"] }
futures = "0.3.34"
smallvec = { version = "1.16.1", features = ["serde"] }
inotify = "0.11.5"
tokio = { version = "1.53.1", features = ["fs", "io-util", "net", "sync", "rt", "time", "macros"] }
libc = "0.2.189"
thiserror = "2.0.20"
tracing = "0.1.44"

[build-dependencies]
bindgen = "0.73.2"
cc = "1.4.6"
pkg-config = "0.3.34"

[lib]
doctest = false

[features]
have_abs_profile = []
